namespace: skaha-system
resources:
- arc-tomcat-deployment.yaml
- arc-tomcat-expose.yaml
- arc-ingress.yaml
configMapGenerator:
- name: arc-config
  files:
  - config/catalina.properties
  - config/cavern.properties
  - config/cadc-registry.properties
  - config/war-rename.conf
  - config/RsaSignaturePub.key
generatorOptions:
 disableNameSuffixHash: true
