apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: {{ .Values.skaha.namespace }}
  name: image-caching-cronjob
spec:
  schedule: "0 */4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: image-caching-cronjob
              image: busybox:1.28
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - image-caching.sh
              env:
                - name: HARBOR_HOST
                  value: "{{ .Values.deployment.skaha.registryHosts }}"
              volumeMounts:
                - name: config-volume
                  mountPath: /config
          restartPolicy: OnFailure
          volumes:
          - name: config-volume
            configMap:
              name: skaha-config