{{- define "skaha.session.commonVolumes" -}}
      {{- if .Values.sessions.extraVolumes }}
      {{- range .Values.sessions.extraVolumes }}
      - name: {{ .name }}
        {{- if eq .volume.type "PVC" }}
        persistentVolumeClaim:
          claimName: {{ .volume.name }}
        {{- else if eq .volume.type "HOST_PATH" }}
        hostPath:
          path: {{ .volume.hostPath }}
          type: {{ .volume.hostPathType }}
        {{- else if eq .volume.type "CONFIG_MAP" }}
        configMap:
          name: {{ .volume.name }}
          {{- if .volumeMount.defaultMode }}
          defaultMode: {{ .volume.defaultMode }}
          {{- end }}
        {{- else if eq .volume.type "SECRET" }}
        secret:
          secretName: {{ .volume.name }}
          {{- if .volumeMount.defaultMode }}
          defaultMode: {{ .volume.defaultMode }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- end }}
      - name: cavern-volume
        persistentVolumeClaim:
          claimName: skaha-workload-cavern-pvc
      - name: scratch-dir
        emptyDir: {}
      - name: etc-group
        emptyDir: {}
      - name: etc-passwd
        emptyDir: {}
      - name: init-users-groups
        configMap:
          name: init-users-groups-config
          defaultMode: 0777
{{- end }}

{{- define "skaha.session.notebookVolumes" -}}
      - name: start-jupyterlab
        configMap:
          name: launch-scripts
          defaultMode: 0777
{{- end }}

{{- define "skaha.session.cartaVolumes" -}}
      - name: start-carta
        configMap:
          name: launch-scripts
          defaultMode: 0777
{{- end }}

{{- define "skaha.session.desktopVolumes" -}}
      - name: templates
        configMap:
          name: templates
          defaultMode: 0777
      - name: start-desktop
        configMap:
          name: launch-scripts
          defaultMode: 0777
{{- end }}

{{- define "skaha.session.desktopAppVolumes" -}}
      - name: start-desktop-software
        configMap:
          name: launch-scripts
          defaultMode: 0777
{{- end }}
