{{- define "skaha.session.commonVolumes" -}}
      - name: cavern-volume
        persistentVolumeClaim:
          claimName: skaha-workload-cavern-pvc
      - name: scratch-dir
        emptyDir: {}
      - name: etc-group
        emptyDir: {}
      - name: etc-passwd
        emptyDir: {}
      - name: init-users-groups
        configMap:
          name: init-users-groups-config
          defaultMode: 0777
{{- end }}

{{- define "skaha.session.notebookVolumes" -}}
      - name: start-jupyterlab
        configMap:
          name: launch-scripts
          defaultMode: 0777
{{- end }}

{{- define "skaha.session.cartaVolumes" -}}
      - name: start-carta
        configMap:
          name: launch-scripts
          defaultMode: 0777
{{- end }}

{{- define "skaha.session.desktopVolumes" -}}
      - name: templates
        configMap:
          name: templates
          defaultMode: 0777
      - name: start-desktop
        configMap:
          name: launch-scripts
          defaultMode: 0777
{{- end }}

{{- define "skaha.session.desktopAppVolumes" -}}
      - name: start-desktop-software
        configMap:
          name: launch-scripts
          defaultMode: 0777
{{- end }}
