{{- define "skaha.session.commonVolumeMounts" -}}
        {{- if .Values.sessions.extraVolumes }}
        {{- range .Values.sessions.extraVolumes }}
        - name: {{ .name }}
          mountPath: {{ .volumeMount.mountPath }}
          {{- if .volumeMount.subPath }}
          subPath: {{ .volumeMount.subPath }}
          {{- end }}
          {{- if .volumeMount.readOnly }}
          readOnly: {{ .volumeMount.readOnly }}
          {{- end }}
          {{- if .volumeMount.mountPropagation }}
          mountPropagation: {{ .volumeMount.mountPropagation }}
          {{- end }}
        {{- end }}
        {{- end }}
        - mountPath: "/etc/passwd"
          name: etc-passwd
          subPath: passwd
        - mountPath: "/etc/group"
          name: etc-group
          subPath: group
        - mountPath: "${SKAHA_TLD}"
          name: cavern-volume
          subPath: "cavern"
        - mountPath: "/scratch"
          name: scratch-dir
          subPath: "${skaha.sessionid}"
{{- end }}

{{- define "skaha.session.cartaVolumeMounts" -}}
        - mountPath: "/skaha-system"
          name: start-carta
{{- end }}


{{- define "skaha.session.desktopAppVolumeMounts" -}}
        - mountPath: "/skaha-system"
          name: start-desktop-software
{{- end }}

{{- define "skaha.session.desktopVolumeMounts" -}}
        - mountPath: "/desktopstartup"
          name: templates
        - mountPath: "/skaha-system"
          name: start-desktop
{{- end }}

{{- define "skaha.session.notebookVolumeMounts" -}}
        - mountPath: "/skaha-system"
          name: start-jupyterlab
{{- end }}
