name: "CD: Edge Build"

on:
  repository_dispatch:
    types: [edge-build]

env:
  REGISTRY: ${{ secrets.CONTAINER_REGISTRY}}
  IMAGE: platform/science-platform
  TAG: edge

jobs:
  edge-build:
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      id-token: write
    steps:
      -
        name: Client Payload
        id: client-payload
        run: |
          echo "Client Payload: ${{ toJson(github.event.client_payload) }}"
      - 
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1
        with:
          install: true
      -
        name: Perform Container Registry Login
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      -
        name: Build and Push Docker Image
        id: build
        uses: docker/build-push-action@v6.9.0
        with:
          context: skaha/
          target: production
          file: skaha/Dockerfile
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: mode=max
          sbom: true
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }}
          labels: |
            org.opencontainers.image.title=Science Platform
            org.opencontainers.image.licenses=AGPL-3.0
            org.opencontainers.image.url=https://github.com/shinybrar/science-platform
      -
        name: Attest Container Image
        id: attest
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true