name: "CI: Commit Check"

on:
  pull_request:
    branches: [main]
  # This check runs on every push to repository
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  commit-check:
    runs-on: ubuntu-latest
    permissions:  # use permissions because of use pr-comments
      contents: read
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # checkout PR HEAD commit
          fetch-depth: 0  # required for merge-base check
      - name: Run Commit Check
        uses: commit-check/commit-check-action@cac2d49b6c81b73cefef7a842f69b872543a18dc # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # use GITHUB_TOKEN because of use pr-comments
        with:
          # Conventional Commits Check
          message: true
          # Convention Branch Check
          branch: false
          author-name: true
          author-email: true
          commit-signoff: false
          merge-base: true
          job-summary: true
          pr-comments: false
