name: "CI: Testing"

on:
    pull_request:
      branches: [main]
    push:
      branches: [main]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350 # v2.10.3
        with:
          egress-policy: audit
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
            fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Run Tests
        run: |
            cd skaha
            ./gradlew clean check
      - name: Upload coverage artifacts
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
        with:
          name: skaha-unittests-coverage
          path: skaha/build/reports/jacoco/test/jacocoTestReport.xml
          if-no-files-found: error
          retention-days: 1
          overwrite: true

  codecov:
    runs-on: ubuntu-latest
    needs: tests
    permissions:
      id-token: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350 # v2.10.3
        with:
          egress-policy: audit
      - name: Download coverage artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: skaha-unittests-coverage
      - name: List Downloaded Artifacts
        run: |
            echo "Downloaded artifacts:"
            ls -lah $GITHUB_WORKSPACE
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@1e68e06f1dbfde0e4cefc87efeba9e4643565303 # v5.1.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: jacocoTestReport.xml
          flags: skaha-unittests-coverage
          name: skaha-unittests-coverage
          fail_ci_if_error: true
          verbose: true
